---
deployment:
  tasks:
    - export DEPLOYPATH=/home/otopleni/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R style.css $DEPLOYPATH
    - /bin/cp -R robots.txt $DEPLOYPATH
    - /bin/cp -R sitemap.xml $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R send.php $DEPLOYPATH
    - /bin/cp -R config.php $DEPLOYPATH
